(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload :sdl2))


(defun game ()
  (sdl2:init :everything)
  (let* ((window (sdl2:create-window :w 400 :h 200))
         (renderer (sdl2:create-renderer window nil (list :accelerated :presentvsync))))
    (sdl2:set-render-draw-color renderer 250 0 250 255)
    (sdl2:render-clear renderer)
    (let ((rect (sdl2:make-rect 10 10 50 50)))
      (sdl2:set-render-draw-color renderer 0 0 0 255)
      (sdl2:render-draw-rect renderer rect))
    (sdl2:render-present renderer)
    (sleep 1)
    (sdl2:destroy-renderer renderer)
    (sdl2:destroy-window window))
  (sdl2:quit))
